routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'MainController@index')->name('main');

Route::resource('products.carts', 'ProductCartController')->only(['store', 'destroy']);

Route::resource('carts', 'CartController')->only(['index']);

Route::resource('orders', 'OrderController')->only(['create', 'store']);

Route::resource('orders.payments', 'OrderPaymentController')->only(['create', 'store']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Cart.php
<?php

namespace App;

use App\Product;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model {
	use HasFactory;

	public function products() {

		return $this->morphToMany(Product::class, 'productable')->withPivot('quantity');
	}

	public function getTotalAttribute() {

		return $this->products->pluck('total')->sum();
	}
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Services\CartService;

class CartController extends Controller {

	public $cartService;

	public function __construct(CartService $cartService) {

		$this->cartService = $cartService;
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		$cart = $this->cartService->getFromCookie();
		return view('carts.index')
			->with(['cart' => $cart]);

	}

}

resources/views/carts/index.blade.php
@extends('layouts.app')

@section('content')
       <h1 class="mb-3">Your Cart</h1>
       @if (!isset($cart) || $cart->products->isEmpty())
           <div class="alert alert-warning">
               Your cart is empty
           </div>
        @else
            <a class="btn btn-success mb-3" href="{{ route('orders.create') }} ">Show your Order</a>

            <div class="row">
                @foreach ($cart->products as $product)
                    <div class="col-3">
                        @include('components.product-card')
                    </div>
                @endforeach

           </div>
       @endif

@endsection