routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'MainController@index')->name('main');

Route::resource('products.carts', 'ProductCartController')->only(['store', 'destroy']);

Route::resource('carts', 'CartController')->only(['index']);

Route::resource('orders', 'OrderController')->only(['create', 'store']);

Route::resource('orders.payments', 'OrderPaymentController')->only(['create', 'store']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Order.php
<?php

namespace App;

use App\Payment;
use App\Product;
use App\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model {
	use HasFactory;

	protected $fillable = [
		'status',
		'customer_id',

	];

	public function payment() {

		return $this->hasOne(Payment::class);
	}

	public function user() {

		return $this->belongsTo(User::class, 'customer_id');
	}

	public function products() {

		return $this->morphToMany(Product::class, 'productable')->withPivot('quantity');
	}

	public function getTotalAttribute() {

		return $this->products->pluck('total')->sum();
	}
}

app/Product.php
<?php

namespace App;

use App\Cart;
use App\Image;
use App\Order;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model {
	use HasFactory;
	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'title',
		'description',
		'price',
		'stock',
		'status',
	];

	public function carts() {

		return $this->morphedByMany(Cart::class, 'productable')->withPivot('quantity');
	}

	public function orders() {

		return $this->morphedByMany(Order::class, 'productable')->withPivot('quantity');
	}

	public function images() {

		return $this->morphMany(Image::class, 'imageable');
	}

	public function scopeAvailable($query) {

		$query->where('status', 'unavailable');
	}

	public function scopeStock($query) {
		$query->where('stock', '>', 5);
	}

	public function getTotalAttribute() {

		return $this->pivot->quantity * $this->price;

	}

}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Services\CartService;
use Illuminate\Http\Request;

class OrderController extends Controller {
	public $cartService;

	public function __construct(CartService $cartService) {

		$this->cartService = $cartService;
		$this->middleware('auth');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

		$cart = $this->cartService->getFromCookie();

		if (!isset($cart) || $cart->products->isEmpty()) {
			return redirect()
				->back()
				->withErrors('Your Cart Is Empty');
		}

		return view('orders.create')->with([
			'cart' => $cart]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$user = $request->user();

		$order = $user->orders()->create([
			'status' => 'pending',
		]);

		$cart = $this->cartService->getFromCookie();

		$cartProductsWithQuantity = $cart
			->products
			->mapWithKeys(function ($product) {
				$element[$product->id] = ['quantity' => $product->pivot->quantity];
				return $element;
			});

		$order->products()->attach($cartProductsWithQuantity->toArray());

		return redirect()->route('orders.payments.create', ['order' => $order]);
	}

}

resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')

 <h1>Order Detail</h1>

<h4 class="text-center"><strong>Total: </strong>${{$cart->total}} </h4>

        <div class="text-center mb-3">
            <form
                method="POST"
                class="d-inline"
                action="{{route('orders.store') }} ">
                @csrf

                <button class="btn btn-success" type="submit">Confirm your Order</button>

            </form>
        </div>
        <div class="table-responsive ">
            <table class="table table-striped ">
                <thead class="thead-light">
                    <tr>

                        <th>Title</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>

                    </tr>
                </thead>
                <tbody >
                    @foreach ($cart->products as $product)
                    <tr>

                        <td>
                            <img src="{{ asset($product->images->first()->path) }} " width="100" class="mr-5">
                            {{ $product->title}}
                        </td>
                        <td >{{ $product->price}} </td>
                        <td>{{ $product->pivot->quantity}} </td>
                        <td>
                            <strong>
                                ${{$product->total }}
                            </strong>
                        </td>

                    </tr>
                    @endforeach

                </tbody>
            </table>
        </div>

@endsection